import React, { useState } from 'react';
import { ChevronDown, ChevronUp, AlertCircle, CheckCircle, Calendar, Target } from 'lucide-react';

interface AnalysisResult {
  analysis: string;
  tabType: string;
  period: {
    year: number;
    quarter: string;
  };
  timestamp: string;
}

interface AnalysisResultsProps {
  result: AnalysisResult | null;
  error: string | null;
}

export const AnalysisResults: React.FC<AnalysisResultsProps> = ({
  result,
  error
}) => {
  const [isExpanded, setIsExpanded] = useState(true);

  if (!result && !error) {
    return null;
  }

  if (error) {
    return (
      <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
        <div className="flex items-center">
          <AlertCircle className="h-5 w-5 text-red-500 mr-2" />
          <span className="text-red-800 font-medium">Analysis Failed</span>
        </div>
        <p className="text-red-600 mt-2">{error}</p>
      </div>
    );
  }

  if (!result) return null;

  const formatTabType = (tabType: string) => {
    const typeMap: Record<string, string> = {
      overview: 'Executive Overview',
      website: 'Website Analytics',
      traffic: 'Traffic Sources',
      social: 'Social Media',
      email: 'Email Marketing',
      leads: 'Leads & Pipeline'
    };
    return typeMap[tabType] || tabType;
  };

  const formatDate = (timestamp: string) => {
    return new Date(timestamp).toLocaleString();
  };

  return (
    <div className="mt-4 bg-gradient-to-br from-blue-50 to-green-50 border border-blue-200 rounded-lg overflow-hidden">
      {/* Header */}
      <div
        className="p-4 bg-gradient-to-r from-caat-blue to-caat-green text-white cursor-pointer flex items-center justify-between"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center">
          <CheckCircle className="h-5 w-5 mr-2" />
          <span className="font-medium">AI Analysis Complete</span>
        </div>
        {isExpanded ? (
          <ChevronUp className="h-5 w-5" />
        ) : (
          <ChevronDown className="h-5 w-5" />
        )}
      </div>

      {/* Content */}
      {isExpanded && (
        <div className="p-6">
          {/* Metadata */}
          <div className="flex flex-wrap items-center gap-4 mb-4 text-sm text-gray-600">
            <div className="flex items-center">
              <Target className="h-4 w-4 mr-1" />
              <span>{formatTabType(result.tabType)}</span>
            </div>
            <div className="flex items-center">
              <Calendar className="h-4 w-4 mr-1" />
              <span>{result.period.quarter} {result.period.year}</span>
            </div>
            <div className="text-xs">
              Generated: {formatDate(result.timestamp)}
            </div>
          </div>

          {/* Analysis Content */}
          <div className="prose prose-sm max-w-none">
            <div className="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
              <div className="whitespace-pre-wrap text-gray-800 leading-relaxed">
                {result.analysis}
              </div>
            </div>
          </div>

          {/* Footer Note */}
          <div className="mt-4 text-xs text-gray-500 italic">
            Analysis generated by Claude AI based on CAAT Pension Plan marketing data.
            Results should be reviewed by marketing professionals before taking action.
          </div>
        </div>
      )}
    </div>
  );
};